### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by HenrikBischkopf** [HenrikBischkopf/HeinS-Ice#1]
## Value proposition
As a ice enthusiast and waffle lover,

I want to have a clear meaning of identifying the best ice-cream parlors in summer and the best waffle houses in winter in my neighbourhood,

so that i am always able to find the best ice-cream & waffle. 

## Description
Image

## Acceptance criteria

- [ ] Users finds a structured landing page, which easy to understand access to other pages and functions.

## Tasks

- [ ] Create the basic code for a landing page with mock tiles linking to yet non-existent pages.
- [ ] Create feature branch feature/landingPageStart
