### ISSUE TITLE
Add file structure

### ISSUE THREAD

**Issue by HenrikBischkopf** [HenrikBischkopf/HeinS-Ice#2]
## Value proposition
As a ice enthusiast and waffle lover,

I want to have a ice-cream parlors and waffle house app,

so that i am always able to find the best ice-cream and waffle.

## Description
Image

## Acceptance criteria

- [ ] Implement basic JS and html files on GitHub and Git.

## Tasks

- [ ] Create the basic code for an app, like a html and js file
- [ ] Create feature branch FirstFiles
