### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by HenrikBischkopf** [HenrikBischkopf/HeinS-Ice#6]
## Value proposition
As an ice and waffle enthusiast
I want to identify with my intrests by a fitting Logo
In order to have an easy access

## Description
Find a fitting logo or create a fittin logo 

## Acceptance criteria
- [ ] Logo appears on the Landing Page

## Tasks
 - [ ] create a feature/logo branch
 - [ ] add your logo to a svg file
 - [ ] link that file as component to your landing page
