### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by HenrikBischkopf** [HenrikBischkopf/HeinS-Ice#9]
## Value proposition
As an ice and waffle enthusiast
I want to have a DarkMode option
In order to have an pleasent experience for my eyes.

## Description
Implement a DarkMode option

## Acceptance criteria
- [ ] DarkMode toggle appears on each page.

## Tasks
 - [ ] create a feature/darkMode branch
 - [ ] create a DarkModeToggle component with useState on/off
 - [ ] check with a media querry for orefered color mode
 - [ ] implement the DarkModeToggle component on your landing page
